#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	/// <summary>
	/// File Attachment
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("fileattachment")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class FileAttachment : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the fileattachment entity
		/// </summary>
		public partial class Fields
		{
			public const string CreatedOn = "createdon";
			public const string FileAttachmentId = "fileattachmentid";
			public const string Id = "fileattachmentid";
			public const string FileName = "filename";
			public const string FileSizeInBytes = "filesizeinbytes";
			public const string iscommittedName = "iscommittedname";
			public const string MimeType = "mimetype";
			public const string ObjectId = "objectid";
			public const string ObjectTypeCode = "objecttypecode";
			public const string ObjectTypeCodeName = "objecttypecodename";
			public const string RegardingFieldName = "regardingfieldname";
			public const string VersionNumber = "versionnumber";
			public const string FileAttachment_dv_test_dv_file = "FileAttachment_dv_test_dv_file";
			public const string dv_test_FileAttachments = "dv_test_FileAttachments";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public FileAttachment() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "fileattachment";
		
		public const string EntityLogicalCollectionName = "fileattachments";
		
		public const string EntitySetName = "fileattachments";
		
		public const int EntityTypeCode = 55;
		
		/// <summary>
		/// Date and time when the attachment was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the file attachment.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("fileattachmentid")]
		public System.Nullable<System.Guid> FileAttachmentId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("fileattachmentid");
			}
			set
			{
				this.SetAttributeValue("fileattachmentid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("fileattachmentid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.FileAttachmentId = value;
			}
		}
		
		/// <summary>
		/// File name of the attachment.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("filename")]
		public string FileName
		{
			get
			{
				return this.GetAttributeValue<string>("filename");
			}
			set
			{
				this.SetAttributeValue("filename", value);
			}
		}
		
		/// <summary>
		/// File size of the attachment in bytes.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("filesizeinbytes")]
		public System.Nullable<long> FileSizeInBytes
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("filesizeinbytes");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscommittedname")]
		public string iscommittedName
		{
			get
			{
				if (this.FormattedValues.Contains("iscommitted"))
				{
					return this.FormattedValues["iscommitted"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// MIME type of the attachment.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mimetype")]
		public string MimeType
		{
			get
			{
				return this.GetAttributeValue<string>("mimetype");
			}
			set
			{
				this.SetAttributeValue("mimetype", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the object with which the attachment is associated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		public Microsoft.Xrm.Sdk.EntityReference ObjectId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("objectid");
			}
			set
			{
				this.SetAttributeValue("objectid", value);
			}
		}
		
		/// <summary>
		/// Type of entity with which the file attachment is associated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objecttypecode")]
		public string ObjectTypeCode
		{
			get
			{
				return this.GetAttributeValue<string>("objecttypecode");
			}
			set
			{
				this.SetAttributeValue("objecttypecode", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objecttypecodename")]
		public string ObjectTypeCodeName
		{
			get
			{
				if (this.FormattedValues.Contains("objecttypecode"))
				{
					return this.FormattedValues["objecttypecode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Regarding attribute schema name of the attachment.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingfieldname")]
		public string RegardingFieldName
		{
			get
			{
				return this.GetAttributeValue<string>("regardingfieldname");
			}
			set
			{
				this.SetAttributeValue("regardingfieldname", value);
			}
		}
		
		/// <summary>
		/// Version number of the file attachment.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N FileAttachment_dv_test_dv_file
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("FileAttachment_dv_test_dv_file")]
		public System.Collections.Generic.IEnumerable<DataverseEntities.dv_test> FileAttachment_dv_test_dv_file
		{
			get
			{
				return this.GetRelatedEntities<DataverseEntities.dv_test>("FileAttachment_dv_test_dv_file", null);
			}
			set
			{
				this.SetRelatedEntities<DataverseEntities.dv_test>("FileAttachment_dv_test_dv_file", null, value);
			}
		}
		
		/// <summary>
		/// N:1 dv_test_FileAttachments
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dv_test_FileAttachments")]
		public DataverseEntities.dv_test dv_test_FileAttachments
		{
			get
			{
				return this.GetRelatedEntity<DataverseEntities.dv_test>("dv_test_FileAttachments", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseEntities.dv_test>("dv_test_FileAttachments", null, value);
			}
		}
	}
}
#pragma warning restore CS1591
